### ISSUE TITLE
[bug] private repository not working

### ISSUE THREAD

**Issue by BenoitLondon** [talegari/pkggraph#3]
the init function stops if repository != NULL and repos = url
it should not.
 I edited init such that it handles my use case repository = "CRAN" and repos = private_url

**Comment by talegari** [comment]
Sorry, I had not noticed this issue. Do let me know the fix so that I can change it else you are welcome for a PR.

**Comment by BenoitLondon** [comment]
actually my case would work if you put the code below line 48 in the init function [here](https://github.com/talegari/pkggraph/blob/8dbbc0249aec759ad78040732cd5a34ca8ad551b/R/init.R#L48) inside braces otherwise when repository is NULL, repos_lookup is not defined and init crashes.
Then I can call init with repository = NULL and repos = c(cran_url, private_url) for example

**Comment by talegari** [comment]
Fixed. https://github.com/talegari/pkggraph/commit/8bd7d8b94f2f22c25866ddc26f689758c0e81dcf

**Comment by rsangole** [comment]
I tried using the version on CRAN today, and I still get this error.
